# ... (other parts of your workflow)

jobs:
  # job to run autograding
  grade:
    name: Autograding
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      
      # Set execute permission
      - name: Set Execute Permission
        run: chmod +x main/java/GoogleBillboard.java

      # Compile GoogleBillboard.java
      - name: Compile GoogleBillboard
        run: javac main/java/GoogleBillboard.java

      # Run GoogleBillboard
      - name: Run GoogleBillboard
        run: java -cp main/java GoogleBillboard

      # run grading
      # add id to step so outputs can be referenced
      - uses: education/autograding@v1
        name: "** Grading and Feedback **"
        id: autograde

    outputs:
      grading-score: ${{ steps.autograde.outputs.Points }}

# ... (other parts of your workflow)
