name: GitHub Classroom Workflow

on:
  push:
    paths:
      - '**/Billboard.java'

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  add_comment_and_run_grading:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Comment
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = 123; // Replace with the issue number you want to comment on
            const comment_body = 'run grading';
            github.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment_body
            });

      - name: Run Autograding
        if: always()
        uses: education/autograding@v1
