# Workflow that runs autograding and builds a points bar for score feedback
# Add
#   <img alt="points bar" align="right" height="36" src="../../blob/status/.github/activity-icons/points-bar.svg" />
# to README.md
name: GitHub Classroom Workflow

on: 
  push:
    branches:
      - '*'
      - '!status'
      - '!feedback'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  # job to run autograding
  grade:
    name: Autograding
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      # Set the correct package structure in the Java file
      - name: Set Package in Java file
        run: echo "package main.java;" > main/java/GoogleBillboard.java

      # Compile GoogleBillboard.java and create JAR file
      - name: Compile and Create JAR
        run: |
          javac main/java/GoogleBillboard.java
          jar cfe GoogleBillboard.jar main/java/GoogleBillboard.java

      # Run the JAR file
      - name: Run JAR file
        run: java -jar GoogleBillboard.jar

      # run grading
      # add id to step so outputs can be referenced
      - uses: education/autograding@v1
        name: "** Grading and Feedback **"
        id: autograde

    outputs:
      grading-score: ${{ steps.autograde.outputs.Points }}
