name: GitHub Classroom Workflow

on: 
  push:
    branches:
      - '*'
      - '!status'
      - '!feedback'

  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grade:
    name: Autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Package and Class in Java file
        run: |
          echo "public class GoogleBillboard {" > $GITHUB_WORKSPACE/main/java/GoogleBillboard
          echo "    public static void main(String[] args) {" >> $GITHUB_WORKSPACE/main/java/GoogleBillboard
          echo "        // Your main method code here" >> $GITHUB_WORKSPACE/main/java/GoogleBillboard
          echo "    }" >> $GITHUB_WORKSPACE/main/java/GoogleBillboard
          echo "}" >> $GITHUB_WORKSPACE/main/java/GoogleBillboard


      - name: Set Permissions
        run: chmod +x $GITHUB_WORKSPACE/main/java/GoogleBillboard

      - name: Compile and Run GoogleBillboard
        run: |
          javac $GITHUB_WORKSPACE/main/java/GoogleBillboard

      - name: Run Grading
        uses: education/autograding@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      grading-score: ${{ steps.autograde.outputs.Points }}
