name: GitHub Classroom Workflow

on: 
  push:
    branches:
      - '*'
      - '!status'
      - '!feedback'

  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grade:
    name: Autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Package and Class in Java file
        run: echo "package main.java; public class GoogleBillboard { }" > $GITHUB_WORKSPACE/main/java/GoogleBillboard.java

      - name: Compile and Run GoogleBillboard
        run: |
              javac $GITHUB_WORKSPACE/main/java/GoogleBillboard.java
              java -cp $GITHUB_WORKSPACE/main/java main/java/GoogleBillboard.java


      - name: Run Grading
        uses: education/autograding@v1
        with:
          name: "** Grading and Feedback **"
          id: autograde

    outputs:
      grading-score: ${{ steps.autograde.outputs.Points }}
