# Workflow that runs autograding and builds a points bar for score feedback
# Add
#   <img alt="points bar" align="right" height="36" src="../../blob/status/.github/activity-icons/points-bar.svg" />
# to README.md
name: GitHub Classroom Workflow

on: 
  push:
    branches:
      - '*'
      - '!status'
      - '!feedback'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  # job to run autograding
  grade:
    name: Autograding
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Permissions
        run: |
          chmod +x $GITHUB_WORKSPACE/main/java/GoogleBillboard.java
          ls -l $GITHUB_WORKSPACE/main/java/GoogleBillboard.java
      
      # Set the correct package structure in the Java file
      - name: Set Package in Java file
        run: echo "package main.java;" > main/java/GoogleBillboard.java

      # Compile and Run GoogleBillboard.java
      - name: Compile and Run GoogleBillboard
        run: |
          javac main/java/GoogleBillboard.java

      # run grading
      # add id to step so outputs can be referenced
      - uses: education/autograding@v1
        name: "** Grading and Feedback **"
        id: autograde

    outputs:
      grading-score: ${{ steps.autograde.outputs.Points }}
