name: GitHub Classroom Workflow

on: 
  push:
    branches:
      - '*'
      - '!status'
      - '!feedback'

  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grade:
    name: Autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Package and Class in Java file
        run: |
          echo "public class GoogleBillboard {" > ${{ github.workspace }}/main/java/GoogleBillboard.java
          echo "    public static void main(String[] args) {" >> ${{ github.workspace }}/main/java/GoogleBillboard.java
          echo "        System.out.println(\"Hello, GitHub Actions!\");" >> ${{ github.workspace }}/main/java/GoogleBillboard.java
          echo "    }" >> ${{ github.workspace }}/main/java/GoogleBillboard.java
          echo "}" >> ${{ github.workspace }}/main/java/GoogleBillboard.java




      - name: Set Permissions
        run: chmod +x ${{ github.workspace }}/main/java/GoogleBillboard.java

      - name: Compile and Run GoogleBillboard
        run: |
              javac ${{ github.workspace }}/main/java/GoogleBillboard.java
              java -cp ${{ github.workspace }}/main/java GoogleBillboard
          
    # run grading
      # add id to step so outputs can be referenced
      - uses: education/autograding@v1
        name: "** Grading and Feedback **"
        id: autograde

    outputs:
      grading-score: ${{ steps.autograde.outputs.Points }}

  # reusable workflow that builds and commits a points bar
  update-points-bar:
    uses: markpatterson27/points-bar/.github/workflows/reusable-workflow.yml@main
    if: always()
    needs: grade
    permissions:
      contents: write
    with:
      points: ${{ needs.grade.outputs.grading-score }}
      path: '.github/activity-icons/points-bar.svg'
      branch: status
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
